option(USE_GME             "Build with Game Music Emulators library" ON)
if(USE_GME)
    if(USE_SYSTEM_AUDIO_LIBRARIES)
        find_path(LIBGME_INCLUDE_DIR "gme.h")
        find_library(LIBGME_LIB NAMES gme)
        find_library(LIBZLIB_LIB NAMES z zlib)
        if(LIBGME_INCLUDE_DIR AND LIBGME_LIB AND LIBZLIB_LIB)
            set(FOUND_GME 1)
        endif()
        message("GME: [${FOUND_GME}] ${LIBGME_INCLUDE_DIR} ${LIBGME_LIB}")
    else()
        set(FOUND_GME 1)
        if(DOWNLOAD_AUDIO_CODECS_DEPENDENCY)
            set(LIBGME_LIB gme)
            set(LIBZLIB_LIB zlib)
        else()
            find_library(LIBGME_LIB NAMES gme
                         HINTS "${AUDIO_CODECS_INSTALL_PATH}/lib")
            find_library(LIBZLIB_LIB NAMES zlib z
                         HINTS "${AUDIO_CODECS_INSTALL_PATH}/lib")
        endif()
    endif()
    if(FOUND_GME)
        message("== using GME ==")
        add_definitions(-DMUSIC_GME)
        if(AUDIO_CODECS_REPO_PATH)
            list(APPEND SDL_MIXER_INCLUDE_PATHS ${AUDIO_CODECS_PATH}/libgme/include)
            list(APPEND SDL_MIXER_INCLUDE_PATHS ${AUDIO_CODECS_PATH}/zlib/include)
        endif()
        list(APPEND SDLMixerX_LINK_LIBS ${LIBGME_LIB} ${LIBZLIB_LIB})
        list(APPEND SDLMixerX_SOURCES
            ${SDLMixerX_SOURCE_DIR}/src/codecs/music_gme.c)
    endif()
endif()
