option(USE_MODPLUG         "Build with ModPlug library" ON)
if(USE_MODPLUG)
    if(USE_SYSTEM_AUDIO_LIBRARIES)
        find_package(ModPlug REQUIRED)
        message("ModPlug: [${ModPlug_FOUND}] ${LIBMODPLUG_INCLUDE_DIR} ${LIBMODPLUG_LIB}")
    else()
        set(ModPlug_FOUND 1)
        if(DOWNLOAD_AUDIO_CODECS_DEPENDENCY)
            set(ModPlug_LIBRARIES modplug)
        else()
            find_library(ModPlug_LIBRARIES NAMES modplug
                         HINTS "${AUDIO_CODECS_INSTALL_PATH}/lib")
        endif()
        set(ModPlug_INCLUDE_DIRS "${AUDIO_CODECS_PATH}/libmodplug/include")
    endif()

    if(ModPlug_FOUND)
        message("== using libModPlug ==")
        add_definitions(-DMUSIC_MOD_MODPLUG -DMODPLUG_STATIC)
        list(APPEND SDL_MIXER_INCLUDE_PATHS ${ModPlug_INCLUDE_DIRS})
        list(APPEND SDLMixerX_LINK_LIBS ${ModPlug_LIBRARIES})
        list(APPEND SDLMixerX_SOURCES
            ${SDLMixerX_SOURCE_DIR}/src/codecs/music_modplug.c)
    else()
        message("== skipping libModPlug ==")
    endif()
endif()
