option(USE_MIKMOD          "Build with MikMod library" OFF)
if(USE_MIKMOD)
    if(USE_SYSTEM_AUDIO_LIBRARIES)
        find_path(LIBMIKMOD_INCLUDE_DIR "mikmod.h")
        find_library(LIBMIKMOD_LIB NAMES mikmod)
        if(LIBMIKMOD_INCLUDE_DIR AND LIBMIKMOD_LIB)
            set(FOUND_MIKMOD 1)
        endif()
        message("MikMod: [${FOUND_MIKMOD}] ${LIBMIKMOD_INCLUDE_DIR} ${LIBMIKMOD_LIB}")
    else()
        set(FOUND_MIKMOD 1)
        if(DOWNLOAD_AUDIO_CODECS_DEPENDENCY)
            set(LIBMIKMOD_LIB mikmod)
        else()
            find_library(LIBMIKMOD_LIB NAMES mikmod
                         HINTS "${AUDIO_CODECS_INSTALL_PATH}/lib")
        endif()
    endif()
    if(FOUND_MIKMOD)
        message("== using MikMod ==")
        add_definitions(-DMUSIC_MOD_MIKMOD)
        if(AUDIO_CODECS_REPO_PATH)
            list(APPEND SDL_MIXER_INCLUDE_PATHS ${AUDIO_CODECS_PATH}/libmikmod/include)
        endif()
        list(APPEND SDLMixerX_LINK_LIBS ${LIBMIKMOD_LIB})
        list(APPEND SDLMixerX_SOURCES
            ${SDLMixerX_SOURCE_DIR}/src/codecs/music_mikmod.c)
    endif()
endif()
