# FIXME: Detect a version of SDL2 for pkg-config script

if(USE_SYSTEM_AUDIO_LIBRARIES OR USE_SYSTEM_SDL2)
    find_package(SDL2 REQUIRED)
    set(LIBSDL2CUSTOM_LIB ${SDL2_LIBRARIES})
    set(LIBSDL2CUSTOM_INCLUDES ${SDL2_INCLUDE_DIRS})
    message("== SDL2: ${SDL2_INCLUDE_DIRS} ${SDL2_LIBRARIES} ==")

else()
    if(DOWNLOAD_AUDIO_CODECS_DEPENDENCY)
        set(LIBSDL2CUSTOM_LIB SDL2${MIX_DEBUG_SUFFIX})
    else()
        set(CMAKE_FIND_LIBRARY_SUFFIXES ${FIND_PREFER_SHARED})
        find_library(LIBSDL2CUSTOM_LIB NAMES SDL2
                     HINTS "${AUDIO_CODECS_INSTALL_PATH}/lib")
    endif()
    set(LIBSDL2CUSTOM_INCLUDES ${AUDIO_CODECS_INSTALL_DIR}/include/SDL2)

endif()

list(APPEND SDLMixerX_LINK_LIBS ${LIBSDL2CUSTOM_LIB})
list(APPEND SDL_MIXER_INCLUDE_PATHS ${LIBSDL2CUSTOM_INCLUDES})
