option(USE_MP3_MAD      "Build with MAD MP3 codec" ON)
option(USE_MP3_MAD_GPL_DITHERING "Enable GPL-Licensed dithering functions for MAD library" ON)
if(USE_MP3_MAD)
    if(USE_SYSTEM_AUDIO_LIBRARIES)
        find_path(LIBMAD_INCLUDE_DIR "mad.h")
        find_library(LIBMAD_LIB NAMES mad)
        if(LIBMAD_INCLUDE_DIR AND LIBMAD_LIB)
            set(FOUND_MAD 1)
        endif()
        message("MAD: [${FOUND_MAD}] ${LIBMAD_INCLUDE_DIR} ${LIBMAD_LIB}")
    else()
        set(FOUND_MAD 1)
        if(DOWNLOAD_AUDIO_CODECS_DEPENDENCY)
            set(LIBMAD_LIB mad)
        else()
            find_library(LIBMAD_LIB NAMES mad
                         HINTS "${AUDIO_CODECS_INSTALL_PATH}/lib")
        endif()
    endif()
    if(FOUND_MAD)
        message("== using MAD ==")
        add_definitions(-DMUSIC_MP3_MAD)
        if(USE_MP3_MAD_GPL_DITHERING)
            add_definitions(-DMUSIC_MP3_MAD_GPL_DITHERING)
        endif()
        list(APPEND SDLMixerX_LINK_LIBS ${LIBMAD_LIB})
        if(AUDIO_CODECS_REPO_PATH)
            list(APPEND SDL_MIXER_INCLUDE_PATHS ${AUDIO_CODECS_PATH}/libmad/include)
        endif()
        list(APPEND SDLMixerX_SOURCES
            ${CMAKE_CURRENT_LIST_DIR}/music_mad.c)
    endif()
endif()
