
option(USE_MP3_MPG123     "[WIP, DON'T USE IT] Build with MPG123 MP3 codec" OFF)
if(USE_MP3_MPG123 AND NOT SDL_MIXER_CLEAR_FOR_ZLIB_LICENSE)
    option(USE_MP3_MPG123_DYNAMIC "Use dynamical loading of MPG123" OFF)

    if(NOT USE_SYSTEM_AUDIO_LIBRARIES)
        # ======= Until AudioCodecs will receive buildable mpg123, detect it externally =======
        message(WARNING "AudioCodecs doesn't ship MPG123 YET, it will be recognized from a system!!!")
    endif()

    find_package(Mpg123 REQUIRED)
    message("MPG123 found in ${MPG123_INCLUDE_DIR} folder")
    if(USE_MP3_MPG123_DYNAMIC)
        list(APPEND SDL_MIXER_DEFINITIONS -DMPG123_DYNAMIC=\"${MPG123_DYNAMIC_LIBRARY}\")
        message("Dynamic MPG123: ${MPG123_DYNAMIC_LIBRARY}")
    endif()

    if(MPG123_FOUND)
        message("== using MPG123 (LGPLv2.1+) ==")
        if(NOT USE_MP3_MPG123_DYNAMIC)
            setLicense(LICENSE_LGPL_2_1p)
        endif()
        list(APPEND SDL_MIXER_DEFINITIONS -DMUSIC_MP3_MPG123)
        list(APPEND SDL_MIXER_INCLUDE_PATHS ${MPG123_INCLUDE_DIRS})
        if(NOT USE_SYSTEM_AUDIO_LIBRARIES OR NOT USE_MP3_MPG123_DYNAMIC)
            list(APPEND SDLMixerX_LINK_LIBS ${MPG123_LIBRARIES})
        endif()
        list(APPEND SDLMixerX_SOURCES ${CMAKE_CURRENT_LIST_DIR}/music_mpg123.c)
    endif()
endif()
